# Generated by Django 3.1.6 on 2021-03-22 22:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pet', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('fond', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_details', models.IntegerField()),
                ('imgs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('birth', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('id_invoice', models.IntegerField()),
            ],
        ),
    ]
