# Generated by Django 3.1.6 on 2021-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zviera', models.IntegerField()),
                ('id_pouzivatel', models.IntegerField()),
                ('datum', models.CharField(max_length=10)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pouzivatel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('narodenie', models.CharField(max_length=20)),
                ('heslo', models.CharField(max_length=255)),
                ('id_faktury', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vlastnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druh', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('plemeno', models.CharField(max_length=50)),
                ('meno', models.CharField(max_length=20)),
                ('vek', models.IntegerField()),
                ('vaha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('potrava', models.CharField(max_length=50)),
                ('popis', models.CharField(max_length=255)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Zviera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pouzivatel', models.IntegerField()),
                ('fond', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_vlastnosti', models.IntegerField()),
                ('obrazky', models.CharField(max_length=255)),
            ],
        ),
    ]
