# Generated by Django 3.1.6 on 2021-03-23 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsApp', '0003_initData'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_invoice',
            field=models.CharField(max_length=100, validators=[django.core.validators.int_list_validator]),
        ),
    ]
