# Generated by Django 3.1.6 on 2021-03-23 15:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsApp', '0004_auto_20210323_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_invoice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=100),
        ),
    ]
