# Generated by Django 3.1.6 on 2021-03-26 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsApp', '0005_auto_20210323_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='imgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(blank=True), size=4),
        ),
    ]
