# Generated by Django 3.1.6 on 2021-03-21 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsApp', '0006_auto_20210321_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zviera',
            name='obrazky',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=4),
        ),
    ]
