# Generated by Django 3.1.6 on 2021-03-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsApp', '0002_init_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlastnosti',
            name='popis',
            field=models.TextField(),
        ),
    ]
