# Generated by Django 3.1.6 on 2021-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsApp', '0004_auto_20210320_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouzivatel',
            name='narodenie',
            field=models.DateField(),
        ),
    ]
